version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 4174:4174

  frontend:
    depends_on:
      - backend
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 4173:4173
